# Generated by Django 4.2.11 on 2025-05-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='category',
            new_name='course',
        ),
    ]
