from django.core.management.base import BaseCommand
from assignments.models import Course  # <-- Correct capitalization!

class Command(BaseCommand):
    help = 'Add default course categories to the database'

    def handle(self, *args, **kwargs):
        courses = [
            "Accounting",
            "Business Administration",
            "Finance",
            "Marketing",
            "Human Resource Management",
            "International Business",
            "Entrepreneurship",
            "Supply Chain Management",
            "Economics",
            "Management Information Systems",
            "Civil Engineering",
            "Mechanical Engineering",
            "Electrical Engineering",
            "Computer Engineering",
            "Software Engineering",
            "Chemical Engineering",
            "Aerospace Engineering",
            "Environmental Engineering",
            "Industrial Engineering",
            "Information Technology",
            "Computer Science",
            "Information Systems",
            "Cybersecurity",
            "Data Science",
            "Artificial Intelligence",
            "Software Development",
            "Network Engineering",
            "Web Development",
            "Medicine",
            "Nursing",
            "Pharmacy",
            "Dentistry",
            "Public Health",
            "Physiotherapy",
            "Biomedical Science",
            "Medical Laboratory Science",
            "Nutrition & Dietetics",
            "Occupational Therapy",
            "Psychology",
            "Sociology",
            "Political Science",
            "Anthropology",
            "International Relations",
            "Social Work",
            "Criminology",
            "Literature",
            "History",
            "Philosophy",
            "Languages & Linguistics",
            "Religious Studies",
            "Communication Studies",
            "Fine Arts",
            "Performing Arts",
            "Biology",
            "Chemistry",
            "Physics",
            "Mathematics",
            "Environmental Science",
            "Geology",
            "Astronomy",
            "Early Childhood Education",
            "Primary Education",
            "Secondary Education",
            "Special Education",
            "Educational Leadership",
            "Law",
            "Legal Studies",
            "International Law",
            "Criminal Justice",
            "Agriculture",
            "Agribusiness",
            "Forestry",
            "Environmental Management",
            "Wildlife Conservation",
            "Architecture",
            "Interior Design",
            "Graphic Design",
            "Industrial Design",
            "Urban Planning",
            "Hospitality Management",
            "Tourism Management",
            "Event Management",
            "Culinary Arts",
            "Journalism",
            "Public Relations",
            "Advertising",
            "Film Studies",
            "Digital Media",
        ]
        for course_name in courses:
                obj, created = Course.objects.get_or_create(name=course_name)
                if created:
                    self.stdout.write(self.style.SUCCESS(f'Added course: {course_name}'))
                else:
                    self.stdout.write(self.style.WARNING(f'Course already exists: {course_name}'))
